import { GetServerSideProps, NextPage } from 'next'
import Head from 'next/head'
import Component from '../components/Component'

export interface  Props {
  data: any
}


const Home: NextPage<Props> = ({data}) => {
  
  return (
    <div>
      <Head>
        <title>Create Next App</title>
        <meta name='description' content='Generated by create next app' />
        <link rel='icon' href='/favicon.ico' />
        {/* <link rel='preconnect' href='https://fonts.googleapis.com' />
        <link rel='preconnect' href='https://fonts.gstatic.com' />
        <link
          href='https://fonts.googleapis.com/css2?family=Raleway:wght@400;600&display=swap'
          rel='stylesheet'
        /> */}
      </Head>
      <div className='text-3xl font-bold text-red-500'>
      <Component data={data.user}  />
      </div>
    </div>
  )
}

export default Home



export const getServerSideProps: GetServerSideProps = async (ctx) => {
  const res = await fetch('http://localhost:3000/api')
  const data = await res.json()
  return {
    props: {
      data,
    },
  }
}