import type { NextPage } from 'next'
import Head from 'next/head'
import Main from './Main'

const Home: NextPage = () => {
  return (
    <div>
      <Head>
        <title>Create Next App</title>
        <meta name='description' content='Generated by create next app' />
        <link rel='icon' href='/favicon.ico' />
        <link rel='preconnect' href='https://fonts.googleapis.com' />
        <link rel='preconnect' href='https://fonts.gstatic.com' crossorigin />
        <link
          href='https://fonts.googleapis.com/css2?family=Raleway:wght@400;600&display=swap'
          rel='stylesheet'
        />
      </Head>
      <div className='text-3xl font-bold text-red-500'>
        <Main />
      </div>
    </div>
  )
}

export default Home
