import { GetStaticProps } from 'next'
import Head from 'next/head'
import Component from './Component'

const Home = () => {
  return (
    <div>
      <Head>
        <title>Create Next App</title>
        <meta name='description' content='Generated by create next app' />
        <link rel='icon' href='/favicon.ico' />
        <link rel='preconnect' href='https://fonts.googleapis.com' />
        <link rel='preconnect' href='https://fonts.gstatic.com' />
        <link
          href='https://fonts.googleapis.com/css2?family=Raleway:wght@400;600&display=swap'
          rel='stylesheet'
        />
      </Head>
      <Component />
      {/* <div className='text-3xl font-bold text-red-500'> */}
      {/* <Main /> */}
      {/* </div> */}
    </div>
  )
}

export default Home
